on second thought, don't use ". $POST_BIBTEX_HOOK", but rather just "$POST_BIBTEX_HOOK" to allow for any sort of executible to be used rather than just a bourne shell script.

diff --git a/latex-mk.in b/latex-mk.in
--- a/latex-mk.in
+++ b/latex-mk.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: latex-mk.in,v 1.15 2003/05/29 09:23:30 dan Exp $
+# $Id: latex-mk.in,v 1.16 2003/05/31 22:39:30 dan Exp $
 #
 # Copyright (c) 2002, 2003 Dan McMahill
 # All rights reserved.
@@ -161,15 +161,13 @@ while test $cnt -lt $MAXITERS ; do
 			# run the post-bibtex hook if its been defined
 			if test "X$POST_BIBTEX_HOOK" != "X" ; then
 			    if test -x $POST_BIBTEX_HOOK ; then
-				exit_status=0
-				. $POST_BIBTEX_HOOK $NAME
-				# the post-bibtex hook script can set
-				# exit_status to a non-zero value to 
-				# abort the run
-				if test $exit_status -ne 0 ; then
+				$POST_BIBTEX_HOOK $NAME
+				rc=$?
+				if test $rc -ne 0 ; then
+				    echo "$POST_BIBTEX_HOOK $NAME failed"
 				    rm -f ${NAME}.dvi ${NAME}.pdf
 				    rm -f $LATEX_MK_LOG
-				    exit $exit_status
+				    exit $rc
 				fi
 			    fi
 			fi
