import the first pass at part of a testsuite.  As a bonus I've already caught a bug with this.  Testsuite still needs to be incorporated into the 'make check' part of the automake build system.

diff --git a/testsuite/run_tests b/testsuite/run_tests
--- a/testsuite/run_tests
+++ b/testsuite/run_tests
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: run_tests,v 1.1 2003/02/02 12:38:33 dan Exp $
+# $Id: run_tests,v 1.2 2003/02/03 03:34:50 dan Exp $
 #
 # Copyright (c) 2003 Dan McMahill
 # All rights reserved.
@@ -34,9 +34,45 @@
 #  SUCH DAMAGE.
 #
 
+regen=no
+while test -n "$1"
+do
+    case "$1"
+    in
 
-LATEX_MK_DIR=  ${top_srcdir}
+    -h|--help)
+	echo "Sorry, help not available for this script yet"
+	exit 0
+	;;
 
+    -r|--regen)
+	# regenerate the 'golden' output files.  Use this with caution.
+	# In particular, all differences should be noted and understood.
+	regen=yes
+	shift
+	;;
+
+    -*)
+	echo "unknown option: $1"
+	exit 1
+	;;
+
+    *)
+	break
+	;;
+
+    esac
+done
+
+if [ "X$regen" = "Xyes" ]; then
+    sufx="ref"
+else
+    sufx="log"
+fi
+
+LATEX_MK_DIR=${top_srcdir:-..}
+
+LATEX_MK_DIR=`cd ${LATEX_MK_DIR} && pwd`
 export LATEX_MK_DIR
 
 #######################################
@@ -47,16 +83,16 @@ export LATEX_MK_DIR
 
 BIBTEX=bibtex
 DVIPDFM=dvipdfm
-DVIPDFM_FLAGS= 
+DVIPDFM_FLAGS=
 DVIPS=dvips
-DVIPS_FLAGS="-Ppdf -j0"
+DVIPS_FLAGS=
 ECHO=echo
 ENV_PROG=env
 FALSE=false
 GV=gv
 GV_FLAGS=
-LATEX-MK=latex-mk
-LATEX-MK_FLAGS=
+LATEX_MK=latex-mk
+LATEX_MK_FLAGS=
 LATEX=latex
 LATEX_ENV=
 LPR=lpr
@@ -73,16 +109,16 @@ VIEWPDF_FLAGS=
 
 export BIBTEX
 export DVIPDFM
-export DVIPDFM_FLAGS+
+export DVIPDFM_FLAGS
 export DVIPS
-export DVIPS_FLAGS+
+export DVIPS_FLAGS
 export ECHO
 export ENV_PROG
 export FALSE
 export GV
 export GV_FLAGS
-export LATEX-MK
-export LATEX-MK_FLAGS
+export LATEX_MK
+export LATEX_MK_FLAGS
 export LATEX
 export LATEX_ENV
 export LPR
@@ -135,4 +171,120 @@ GMAKE=${GMAKE:-gmake}
 #
 #
 #######################################
+BMKF=testfile.mk
+GMKF=testfile.gmk
+MFLAGS="LATEX_MK_DIR=${LATEX_MK_DIR} -n"
+BMAKE="${BMAKE} -f ../${BMKF} ${MFLAGS}"
+GMAKE="${GMAKE} -f ../${GMKF} ${MFLAGS}"
+# echo "BSD make command = $BMAKE"
+# echo "GNU make command = $GMAKE"
+
+here=`pwd`
+rundir=${here}/run
+
+if [ ! -d bmake ]; then
+    mkdir bmake
+fi
+if [ ! -d gmake ]; then
+    mkdir gmake
+fi
+
+TESTLIST=tests.list
+
+if [ ! -f $TESTLIST ]; then
+    echo "ERROR: ($0)  Test list $TESTLIST does not exist"
+    exit 1
+fi
+
+# fail/pass/total counts
+bfail=0
+gfail=0
+bpass=0
+gpass=0
+bskip=0
+gskip=0
+tot=0
+
+if test -z "$1" ; then
+    all_tests=`awk 'BEGIN{FS="|"} /^#/{next} {gsub(/ /,""); print $1}' $TESTLIST`
+else
+    all_tests=$*
+fi
+
+for t in $all_tests ; do
+
+    dirs=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $2}'`
+    files=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $3}'`
+    args=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $4}'`
+
+    tot=`expr $tot + 1`
+
+    # create temporary run directory
+    if [ ! -d $rundir ]; then
+	mkdir -p $rundir
+    fi
+
+    # Create the subdirectories needed
+    if [ ! -z "$dirs" ]; then
+	for dir in $dirs ; do
+	    mkdir -p ${rundir}/${dir}
+	done
+    fi
+
+    # Create the files needed
+    if [ ! -z "$files" ]; then
+	for f in $files ; do
+	    touch ${rundir}/${f}
+	done
+    fi
+    
+    # run the BSD make test
+    echo "Test:  (BSD make) $t"
+    cd ${rundir} && ${BMAKE}  $args > ${here}/bmake/${t}.${sufx}
+    if [ "X$regen" != "Xyes" ]; then
+	if [ -f ${here}/bmake/${t}.ref ]; then
+	    if diff ${here}/bmake/${t}.ref ${here}/bmake/${t}.log >/dev/null ; then
+		echo "PASS"
+		bpass=`expr $bpass + 1`
+	    else
+		echo "FAILED:  See diff ${here}/bmake/${t}.ref ${here}/bmake/${t}.log"
+		bfail=`expr $bfail + 1`
+	    fi
+	else
+	    echo "No reference file.  Skipping"
+	    bskip=`expr $bskip + 1`
+	fi
+    else
+	echo "Regenerated"
+    fi
+
+    # run the GNU make test
+    echo "Test:  (GNU make) $t"
+    cd ${rundir} && ${GMAKE}  $args > ${here}/gmake/${t}.${sufx}
+    if [ "X$regen" != "Xyes" ]; then
+	if [ -f ${here}/gmake/${t}.ref ]; then
+	    if diff ${here}/gmake/${t}.ref ${here}/gmake/${t}.log >/dev/null ; then
+		echo "PASS"
+		gpass=`expr $gpass + 1`
+	    else
+		echo "FAILED:  See diff ${here}/gmake/${t}.ref ${here}/gmake/${t}.log"
+		gfail=`expr $gfail + 1`
+	    fi
+	else
+	    echo "No reference file.  Skipping"
+	    gskip=`expr $gskip + 1`
+	fi
+    else
+	echo "Regenerated"
+    fi
+
+    cd $here
+    
+    # clean up the rundirectory
+    #rm -fr ${rundir}
+
+done
+
+echo "BSD make version:  Passed $bpass, failed $bfail, skipped $bskip out of $tot tests."
+echo "GNU make version:  Passed $gpass, failed $gfail, skipped $gskip out of $tot tests."
 
